config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"

  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :comment, presence: true
  validates :rating, presence: true, inclusion: { in: [1, 2, 3, 4, 5] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(list: @list)
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @review = Review.new

    if @bookmark.save
      redirect_to list_path(@bookmark.list)
    else
      render "lists/show"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])

    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index 
    @lists = List.all
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new(list: @list)
  end

  def create
    @lists = List.all
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render "lists/index"
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @review = Review.new(list: @list)
  end

  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    @bookmark = Bookmark.new

    if @review.save
      redirect_to list_path(@review.list)
    else
      render "lists/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark:</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "partials/navbar" %>
    <%= yield %>
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner lists-banner">
</div>
<div class="banner-info">
  <h1 id="h1-banner-list" data-controller="typed-js"></h1>
</div>

<div class="container">
  <div class="lists-grid">
    <div class="list-card black-card" data-controller="form-dropdown" data-action="click->form-dropdown#clickAddMovie" data-aos="zoom-in" data-aos-duration="2000">
      <p class="add-movie-btn", data-form-dropdown-target="moviebutton">Add a List</p>
      
      <div class="d-none movie-form" data-form-dropdown-target="form">
        <%= simple_form_for [@list] do |f| %>
          <%= f.input :name, input_html: { class: 'input-form' } %>
          <%= f.input :photo, as: :file, input_html: { class: 'input-form' } %>
          <%= f.button :submit, class:"add-movie-btn form-btn" %>
        <% end %>
      </div>
    </div>
    
    <% @lists.each do |list| %>
        <div class="list-card" style="background-image: url('<%= cl_image_path list.photo.key, crop: :fill %>')" data-aos="zoom-in" data-aos-duration="2000">
          <%= link_to list.name, list_path(list) %>
        </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New list:</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.button :submit %>
<% end %>

<%= link_to "Back", lists_path %>

app/views/lists/partials/_movie_card.html.erb
<div class="movie-card" data-aos="zoom-in" data-aos-duration="2000">
  <div class="movie-img" style="background-image: url('<%= bookmark.movie.poster_url %>')">
  </div>
  <div class="movie-desc">
    <p class="movie-title m-0"><strong><%= bookmark.movie.title %></strong> • <%= bookmark.movie.rating %> ⭐️</p>
    <p class="movie-overview"><%= bookmark.movie.overview %></p>
    <div class="blockquote">
      <blockquote><%= bookmark.comment %></blockquote>
    </div>
    <div class="delete-movie">
      <%= link_to "delete", bookmark_path(bookmark), method: :delete, class: "delete-link", data: {confirm: "Are you sure?"} %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: url('<%= cl_image_path @list.photo.key, crop: :fill %>')">
</div>
<div class="banner-info">
  <h1><%= @list[:name] %></h1>
</div>

<div class="container">
  <div class="movie-cards-grid mb-4 mt-4">
    <div class="movie-card black-card" data-controller="form-dropdown" data-action="click->form-dropdown#clickAddMovie" data-aos="zoom-in" data-aos-duration="2000">
      <p class="add-movie-btn", data-form-dropdown-target="moviebutton">Add a Movie</p>
      
      <div class="d-none movie-form" data-form-dropdown-target="form">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, input_html: { class: 'input-form' } %>
          <%= f.association :movie, input_html: { class: 'input-form' } %>
          <%= f.button :submit, class:"add-movie-btn form-btn" %>
        <% end %>
      </div>
    </div>

    <% @list.bookmarks.each do |bookmark| %>
      <%= render "lists/partials/movie_card", bookmark: bookmark %>
    <% end %>
  </div>

  <hr>

  <div class="row reviews">
    <div class="col-6 pe-4 border-right-white">
      <h2>Reviews</h2>
      <% @list.reviews.each do |review| %>
        <p class="review-desc">
          <%= "⭐️" * review.rating.to_i %><span>less than <%= (Time.now - review.created_at) / 1.minutes < 60 ? "#{((Time.now - review.created_at) / 1.minutes ).round} minutes ago" : "#{((Time.now - review.created_at) / 1.hours).round} hours ago" %></span></p>
        <p class="review-comment"><%= review.comment %></p>
      <% end %>
    </div>
    <div class="col-6 ps-4 border-left-white">
      <%= simple_form_for [@list, @review] do |f| %>
        <%= f.input :comment, input_html: { class: 'input-form' } %>
        <%= f.input :rating, input_html: { class: 'input-form' } %>
        <%= f.button :submit, class: "add-comment-btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<div class="navbar-lewagon navbar-collapse sticky-top" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <%= link_to "MovieTime", root_path, class: "navbar-brand logo" %>

  <div>
    <%= link_to "My Lists", lists_path, class: "navbar-brand lists" %>
  </div>
</div>